// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ActivatedMembershipStatus.
const (
	Active ActivatedMembershipStatus = "active"
)

// Valid indicates whether the value is a known member of the ActivatedMembershipStatus enum.
func (e ActivatedMembershipStatus) Valid() bool {
	switch e {
	case Active:
		return true
	default:
		return false
	}
}

// Defines values for CreatedTenantKind.
const (
	CreatedTenantKindBusiness CreatedTenantKind = "business"
)

// Valid indicates whether the value is a known member of the CreatedTenantKind enum.
func (e CreatedTenantKind) Valid() bool {
	switch e {
	case CreatedTenantKindBusiness:
		return true
	default:
		return false
	}
}

// Defines values for CreatedTenantRole.
const (
	CreatedTenantRoleOwner CreatedTenantRole = "owner"
)

// Valid indicates whether the value is a known member of the CreatedTenantRole enum.
func (e CreatedTenantRole) Valid() bool {
	switch e {
	case CreatedTenantRoleOwner:
		return true
	default:
		return false
	}
}

// Defines values for MembershipInvitationStatus.
const (
	Invited MembershipInvitationStatus = "invited"
)

// Valid indicates whether the value is a known member of the MembershipInvitationStatus enum.
func (e MembershipInvitationStatus) Valid() bool {
	switch e {
	case Invited:
		return true
	default:
		return false
	}
}

// Defines values for MembershipRole.
const (
	MembershipRoleAdmin         MembershipRole = "admin"
	MembershipRoleBillingMember MembershipRole = "billing_member"
	MembershipRoleMember        MembershipRole = "member"
)

// Valid indicates whether the value is a known member of the MembershipRole enum.
func (e MembershipRole) Valid() bool {
	switch e {
	case MembershipRoleAdmin:
		return true
	case MembershipRoleBillingMember:
		return true
	case MembershipRoleMember:
		return true
	default:
		return false
	}
}

// Defines values for SystemStatusStatus.
const (
	Available SystemStatusStatus = "available"
)

// Valid indicates whether the value is a known member of the SystemStatusStatus enum.
func (e SystemStatusStatus) Valid() bool {
	switch e {
	case Available:
		return true
	default:
		return false
	}
}

// Defines values for TenantSummaryKind.
const (
	TenantSummaryKindBusiness TenantSummaryKind = "business"
	TenantSummaryKindPersonal TenantSummaryKind = "personal"
)

// Valid indicates whether the value is a known member of the TenantSummaryKind enum.
func (e TenantSummaryKind) Valid() bool {
	switch e {
	case TenantSummaryKindBusiness:
		return true
	case TenantSummaryKindPersonal:
		return true
	default:
		return false
	}
}

// Defines values for TenantSummaryRole.
const (
	TenantSummaryRoleAdmin         TenantSummaryRole = "admin"
	TenantSummaryRoleBillingMember TenantSummaryRole = "billing_member"
	TenantSummaryRoleMember        TenantSummaryRole = "member"
	TenantSummaryRoleOwner         TenantSummaryRole = "owner"
)

// Valid indicates whether the value is a known member of the TenantSummaryRole enum.
func (e TenantSummaryRole) Valid() bool {
	switch e {
	case TenantSummaryRoleAdmin:
		return true
	case TenantSummaryRoleBillingMember:
		return true
	case TenantSummaryRoleMember:
		return true
	case TenantSummaryRoleOwner:
		return true
	default:
		return false
	}
}

// ActivatedMembership defines model for ActivatedMembership.
type ActivatedMembership struct {
	// Role The non-owner membership role an invitation grants. owner is not invitable: ownership changes are out of scope for invitations.
	Role MembershipRole `json:"role"`

	// Status The activated state the acceptance transitioned into.
	Status ActivatedMembershipStatus `json:"status"`

	// TenantId The tenant of the accepted membership.
	TenantId openapi_types.UUID `json:"tenant_id"`
}

// ActivatedMembershipStatus The activated state the acceptance transitioned into.
type ActivatedMembershipStatus string

// CreateTenantRequest defines model for CreateTenantRequest.
type CreateTenantRequest struct {
	// DisplayName The business tenant's human-readable display name.
	DisplayName string `json:"display_name"`
}

// CreatedTenant defines model for CreatedTenant.
type CreatedTenant struct {
	// CreatedAt When the tenant was created.
	CreatedAt time.Time `json:"created_at"`

	// DisplayName The created tenant's display name, echoed back.
	DisplayName string `json:"display_name"`

	// Kind The tenant kind (T04 provisions business tenants only).
	Kind CreatedTenantKind `json:"kind"`

	// Role The membership role the creator holds in the new tenant.
	Role CreatedTenantRole `json:"role"`

	// TenantId The created tenant's immutable identifier.
	TenantId openapi_types.UUID `json:"tenant_id"`
}

// CreatedTenantKind The tenant kind (T04 provisions business tenants only).
type CreatedTenantKind string

// CreatedTenantRole The membership role the creator holds in the new tenant.
type CreatedTenantRole string

// MembershipInvitation defines model for MembershipInvitation.
type MembershipInvitation struct {
	// InvitedAt When the invitation was created.
	InvitedAt time.Time `json:"invited_at"`

	// Role The non-owner membership role an invitation grants. owner is not invitable: ownership changes are out of scope for invitations.
	Role MembershipRole `json:"role"`

	// Status The pending state: the membership row exists but is not yet usable at the tenant-context seam.
	Status MembershipInvitationStatus `json:"status"`

	// TenantId The tenant the invitation grants membership in.
	TenantId openapi_types.UUID `json:"tenant_id"`
}

// MembershipInvitationStatus The pending state: the membership row exists but is not yet usable at the tenant-context seam.
type MembershipInvitationStatus string

// MembershipInvitationRequest defines model for MembershipInvitationRequest.
type MembershipInvitationRequest struct {
	// InviteeSubject The invitee's external subject — the identity provider's sub claim of an already-bound user.
	InviteeSubject string `json:"invitee_subject"`

	// Role The non-owner membership role an invitation grants. owner is not invitable: ownership changes are out of scope for invitations.
	Role MembershipRole `json:"role"`
}

// MembershipRole The non-owner membership role an invitation grants. owner is not invitable: ownership changes are out of scope for invitations.
type MembershipRole string

// SelectedTenantContext defines model for SelectedTenantContext.
type SelectedTenantContext struct {
	// SelectedAt When the selection was persisted or last switched.
	SelectedAt time.Time `json:"selected_at"`

	// TenantId The persisted, server-validated selected tenant.
	TenantId openapi_types.UUID `json:"tenant_id"`
}

// SystemStatus defines model for SystemStatus.
type SystemStatus struct {
	// Status Fixed availability marker for the platform service.
	Status SystemStatusStatus `json:"status"`

	// Version Build version of the running platform service.
	Version string `json:"version"`
}

// SystemStatusStatus Fixed availability marker for the platform service.
type SystemStatusStatus string

// TenantContextSelection defines model for TenantContextSelection.
type TenantContextSelection struct {
	// TenantId The tenant being selected.
	TenantId openapi_types.UUID `json:"tenant_id"`
}

// TenantList defines model for TenantList.
type TenantList struct {
	// Tenants Every tenant with an active membership for the user.
	Tenants []TenantSummary `json:"tenants"`
}

// TenantSummary defines model for TenantSummary.
type TenantSummary struct {
	// Kind The tenant kind (migration 000003 vocabulary).
	Kind TenantSummaryKind `json:"kind"`

	// Role The membership role the user holds in the tenant.
	Role TenantSummaryRole `json:"role"`

	// TenantId The tenant's immutable identifier.
	TenantId openapi_types.UUID `json:"tenant_id"`
}

// TenantSummaryKind The tenant kind (migration 000003 vocabulary).
type TenantSummaryKind string

// TenantSummaryRole The membership role the user holds in the tenant.
type TenantSummaryRole string

// CreateTenantParams defines parameters for CreateTenant.
type CreateTenantParams struct {
	// IdempotencyKey Client-chosen retry key: redelivering the same key (with the same authenticated user) converges onto the already-created tenant.
	IdempotencyKey string `json:"Idempotency-Key"`
}

// CreateMembershipInvitationParams defines parameters for CreateMembershipInvitation.
type CreateMembershipInvitationParams struct {
	// IdempotencyKey Client-chosen retry key, required before any write is attempted. Replay convergence rides the (tenant, invitee) natural key: a repeat delivery of a still-pending invitation answers 200 with the same invitation facts.
	IdempotencyKey string `json:"Idempotency-Key"`
}

// PutTenantContextJSONRequestBody defines body for PutTenantContext for application/json ContentType.
type PutTenantContextJSONRequestBody = TenantContextSelection

// CreateTenantJSONRequestBody defines body for CreateTenant for application/json ContentType.
type CreateTenantJSONRequestBody = CreateTenantRequest

// CreateMembershipInvitationJSONRequestBody defines body for CreateMembershipInvitation for application/json ContentType.
type CreateMembershipInvitationJSONRequestBody = MembershipInvitationRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// GetSystemStatus Report whether the platform service is available.
	// (GET /api/v1/system/status)
	GetSystemStatus(c *gin.Context)
	// GetTenantContext Return the server-validated current tenant context selection.
	// (GET /api/v1/tenant-context)
	GetTenantContext(c *gin.Context)
	// PutTenantContext Select or switch the current tenant context.
	// (PUT /api/v1/tenant-context)
	PutTenantContext(c *gin.Context)
	// ListTenants List the tenants the authenticated user holds an active membership in.
	// (GET /api/v1/tenants)
	ListTenants(c *gin.Context)
	// CreateTenant Create a business tenant owned by the authenticated user.
	// (POST /api/v1/tenants)
	CreateTenant(c *gin.Context, params CreateTenantParams)
	// CreateMembershipInvitation Invite a bound user into a tenant as a non-owner member; the membership activates only after the invitee accepts (T05).
	// (POST /api/v1/tenants/{tenantId}/membership-invitations)
	CreateMembershipInvitation(c *gin.Context, tenantId openapi_types.UUID, params CreateMembershipInvitationParams)
	// AcceptMembershipInvitation Accept the pending membership invitation as the invitee.
	// (POST /api/v1/tenants/{tenantId}/membership-invitations/acceptance)
	AcceptMembershipInvitation(c *gin.Context, tenantId openapi_types.UUID)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetSystemStatus operation middleware
func (siw *ServerInterfaceWrapper) GetSystemStatus(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetSystemStatus(c)
}

// GetTenantContext operation middleware
func (siw *ServerInterfaceWrapper) GetTenantContext(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetTenantContext(c)
}

// PutTenantContext operation middleware
func (siw *ServerInterfaceWrapper) PutTenantContext(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PutTenantContext(c)
}

// ListTenants operation middleware
func (siw *ServerInterfaceWrapper) ListTenants(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListTenants(c)
}

// CreateTenant operation middleware
func (siw *ServerInterfaceWrapper) CreateTenant(c *gin.Context) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateTenantParams

	headers := c.Request.Header

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for Idempotency-Key, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter Idempotency-Key: %w", err), http.StatusBadRequest)
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter Idempotency-Key is required, but not found"), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateTenant(c, params)
}

// CreateMembershipInvitation operation middleware
func (siw *ServerInterfaceWrapper) CreateMembershipInvitation(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "tenantId" -------------
	var tenantId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "tenantId", c.Param("tenantId"), &tenantId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter tenantId: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateMembershipInvitationParams

	headers := c.Request.Header

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for Idempotency-Key, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter Idempotency-Key: %w", err), http.StatusBadRequest)
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter Idempotency-Key is required, but not found"), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateMembershipInvitation(c, tenantId, params)
}

// AcceptMembershipInvitation operation middleware
func (siw *ServerInterfaceWrapper) AcceptMembershipInvitation(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "tenantId" -------------
	var tenantId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "tenantId", c.Param("tenantId"), &tenantId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter tenantId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.AcceptMembershipInvitation(c, tenantId)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/api/v1/system/status", wrapper.GetSystemStatus)
	router.GET(options.BaseURL+"/api/v1/tenants", wrapper.ListTenants)
	router.POST(options.BaseURL+"/api/v1/tenants", wrapper.CreateTenant)
	router.GET(options.BaseURL+"/api/v1/tenant-context", wrapper.GetTenantContext)
	router.PUT(options.BaseURL+"/api/v1/tenant-context", wrapper.PutTenantContext)
	router.POST(options.BaseURL+"/api/v1/tenants/:tenantId/membership-invitations", wrapper.CreateMembershipInvitation)
	router.POST(options.BaseURL+"/api/v1/tenants/:tenantId/membership-invitations/acceptance", wrapper.AcceptMembershipInvitation)
}

type GetSystemStatusRequestObject struct {
}

type GetSystemStatusResponseObject interface {
	VisitGetSystemStatusResponse(w http.ResponseWriter) error
}

type GetSystemStatus200JSONResponse SystemStatus

func (response GetSystemStatus200JSONResponse) VisitGetSystemStatusResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetTenantContextRequestObject struct {
}

type GetTenantContextResponseObject interface {
	VisitGetTenantContextResponse(w http.ResponseWriter) error
}

type GetTenantContext200JSONResponse SelectedTenantContext

func (response GetTenantContext200JSONResponse) VisitGetTenantContextResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type PutTenantContextRequestObject struct {
	Body *PutTenantContextJSONRequestBody
}

type PutTenantContextResponseObject interface {
	VisitPutTenantContextResponse(w http.ResponseWriter) error
}

type PutTenantContext200JSONResponse SelectedTenantContext

func (response PutTenantContext200JSONResponse) VisitPutTenantContextResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListTenantsRequestObject struct {
}

type ListTenantsResponseObject interface {
	VisitListTenantsResponse(w http.ResponseWriter) error
}

type ListTenants200JSONResponse TenantList

func (response ListTenants200JSONResponse) VisitListTenantsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type CreateTenantRequestObject struct {
	Params CreateTenantParams
	Body   *CreateTenantJSONRequestBody
}

type CreateTenantResponseObject interface {
	VisitCreateTenantResponse(w http.ResponseWriter) error
}

type CreateTenant200JSONResponse CreatedTenant

func (response CreateTenant200JSONResponse) VisitCreateTenantResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type CreateTenant201JSONResponse CreatedTenant

func (response CreateTenant201JSONResponse) VisitCreateTenantResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateMembershipInvitationRequestObject struct {
	TenantId openapi_types.UUID `json:"tenantId"`
	Params   CreateMembershipInvitationParams
	Body     *CreateMembershipInvitationJSONRequestBody
}

type CreateMembershipInvitationResponseObject interface {
	VisitCreateMembershipInvitationResponse(w http.ResponseWriter) error
}

type CreateMembershipInvitation200JSONResponse MembershipInvitation

func (response CreateMembershipInvitation200JSONResponse) VisitCreateMembershipInvitationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type CreateMembershipInvitation201JSONResponse MembershipInvitation

func (response CreateMembershipInvitation201JSONResponse) VisitCreateMembershipInvitationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type AcceptMembershipInvitationRequestObject struct {
	TenantId openapi_types.UUID `json:"tenantId"`
}

type AcceptMembershipInvitationResponseObject interface {
	VisitAcceptMembershipInvitationResponse(w http.ResponseWriter) error
}

type AcceptMembershipInvitation200JSONResponse ActivatedMembership

func (response AcceptMembershipInvitation200JSONResponse) VisitAcceptMembershipInvitationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// GetSystemStatus Report whether the platform service is available.
	// (GET /api/v1/system/status)
	GetSystemStatus(ctx context.Context, request GetSystemStatusRequestObject) (GetSystemStatusResponseObject, error)
	// GetTenantContext Return the server-validated current tenant context selection.
	// (GET /api/v1/tenant-context)
	GetTenantContext(ctx context.Context, request GetTenantContextRequestObject) (GetTenantContextResponseObject, error)
	// PutTenantContext Select or switch the current tenant context.
	// (PUT /api/v1/tenant-context)
	PutTenantContext(ctx context.Context, request PutTenantContextRequestObject) (PutTenantContextResponseObject, error)
	// ListTenants List the tenants the authenticated user holds an active membership in.
	// (GET /api/v1/tenants)
	ListTenants(ctx context.Context, request ListTenantsRequestObject) (ListTenantsResponseObject, error)
	// CreateTenant Create a business tenant owned by the authenticated user.
	// (POST /api/v1/tenants)
	CreateTenant(ctx context.Context, request CreateTenantRequestObject) (CreateTenantResponseObject, error)
	// CreateMembershipInvitation Invite a bound user into a tenant as a non-owner member; the membership activates only after the invitee accepts (T05).
	// (POST /api/v1/tenants/{tenantId}/membership-invitations)
	CreateMembershipInvitation(ctx context.Context, request CreateMembershipInvitationRequestObject) (CreateMembershipInvitationResponseObject, error)
	// AcceptMembershipInvitation Accept the pending membership invitation as the invitee.
	// (POST /api/v1/tenants/{tenantId}/membership-invitations/acceptance)
	AcceptMembershipInvitation(ctx context.Context, request AcceptMembershipInvitationRequestObject) (AcceptMembershipInvitationResponseObject, error)
}

type StrictHandlerFunc func(ctx *gin.Context, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictGinServerOptions struct {
	// RequestErrorHandlerFunc is called when a request cannot be parsed or
	// decoded. It is invoked for JSON bind failures, form parse/bind errors,
	// multipart reader errors, media type parse errors, missing multipart
	// boundaries, and request body read errors. The default returns 400.
	RequestErrorHandlerFunc func(ctx *gin.Context, err error)
	// HandlerErrorFunc is called when the application handler (or any
	// middleware wrapping it) returns a non-nil error. The default returns 500.
	HandlerErrorFunc func(ctx *gin.Context, err error)
	// ResponseErrorHandlerFunc is called when the response object fails to
	// serialize (Visit*Response returns an error) or when the handler returns
	// an unexpected response type. The default returns 500.
	ResponseErrorHandlerFunc func(ctx *gin.Context, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictGinServerOptions{
		RequestErrorHandlerFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusBadRequest, gin.H{"msg": err.Error()})
		},
		HandlerErrorFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		},
		ResponseErrorHandlerFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictGinServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusBadRequest, gin.H{"msg": err.Error()})
		}
	}
	if options.HandlerErrorFunc == nil {
		options.HandlerErrorFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictGinServerOptions
}

// GetSystemStatus operation middleware
func (sh *strictHandler) GetSystemStatus(ctx *gin.Context) {
	var request GetSystemStatusRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetSystemStatus(ctx, request.(GetSystemStatusRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetSystemStatus")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(GetSystemStatusResponseObject); ok {
		if err := validResponse.VisitGetSystemStatusResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetTenantContext operation middleware
func (sh *strictHandler) GetTenantContext(ctx *gin.Context) {
	var request GetTenantContextRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetTenantContext(ctx, request.(GetTenantContextRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetTenantContext")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(GetTenantContextResponseObject); ok {
		if err := validResponse.VisitGetTenantContextResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PutTenantContext operation middleware
func (sh *strictHandler) PutTenantContext(ctx *gin.Context) {
	var request PutTenantContextRequestObject

	var body PutTenantContextJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PutTenantContext(ctx, request.(PutTenantContextRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PutTenantContext")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(PutTenantContextResponseObject); ok {
		if err := validResponse.VisitPutTenantContextResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListTenants operation middleware
func (sh *strictHandler) ListTenants(ctx *gin.Context) {
	var request ListTenantsRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListTenants(ctx, request.(ListTenantsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListTenants")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(ListTenantsResponseObject); ok {
		if err := validResponse.VisitListTenantsResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateTenant operation middleware
func (sh *strictHandler) CreateTenant(ctx *gin.Context, params CreateTenantParams) {
	var request CreateTenantRequestObject

	request.Params = params

	var body CreateTenantJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateTenant(ctx, request.(CreateTenantRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateTenant")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(CreateTenantResponseObject); ok {
		if err := validResponse.VisitCreateTenantResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateMembershipInvitation operation middleware
func (sh *strictHandler) CreateMembershipInvitation(ctx *gin.Context, tenantId openapi_types.UUID, params CreateMembershipInvitationParams) {
	var request CreateMembershipInvitationRequestObject

	request.TenantId = tenantId
	request.Params = params

	var body CreateMembershipInvitationJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateMembershipInvitation(ctx, request.(CreateMembershipInvitationRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateMembershipInvitation")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(CreateMembershipInvitationResponseObject); ok {
		if err := validResponse.VisitCreateMembershipInvitationResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// AcceptMembershipInvitation operation middleware
func (sh *strictHandler) AcceptMembershipInvitation(ctx *gin.Context, tenantId openapi_types.UUID) {
	var request AcceptMembershipInvitationRequestObject

	request.TenantId = tenantId

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.AcceptMembershipInvitation(ctx, request.(AcceptMembershipInvitationRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AcceptMembershipInvitation")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(AcceptMembershipInvitationResponseObject); ok {
		if err := validResponse.VisitAcceptMembershipInvitationResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"zFrrbuO4FX6VA3WBSQD5MjPbovX8yk5vQXfRNDFQtIM0oMVjixuJ1JCUHTUw0IfoE/ZJikNSN1uO48xk",
	"sPtnM5bEc/vOdz5SeowSlRdKorQmmj1GJkkxZ+7Pi8SKNbPIf8J8gdqkoqCfGefCCiVZdqVVgdoKNNFs",
	"yTKDcVR0fnqMtMqQ/v+dxmU0i341aW1NgqFJu/g13b2NI2OZLd3ziZLGRrOIkScYxRFHk2hRkPloFs1T",
	"BFY7CfQYgnW/JVhYJhMEq5k0zl3kIKRV4yiObFVgNIuM1UKuyKJFyaS9E5yM7tvwl0EtO6sjh7zxnBZd",
	"Kp0zcrYsBd83so0jjZ9LoZFHs08di7HPUhP2bfOoWvyMiSX/PmpkFufumWv8XCJl5aRKcGGKjFV3kuU4",
	"HOSiNEKiMSHaNwbSMmdypJFxtsgQwhJAS1DAOXv4EeXKptHs7XQaR7mQzb+Phd9z53DE3Id8YqyJf/aO",
	"2f1I/56idFUMNd0wA+H+XhE5sziyIschuBxPZliyzWU3eTFgkirksGDJ/SAe74XkXfzXtRnsgBAJPQNn",
	"8+n3UGi1FkYoaXaLakDJrDoftFn3am1TbSTqQYMt7oEecul0ASsNqcq4AeFzLHETDL+k6/ZyKPK8tA6K",
	"gqO0YilQf1nnuTzv1DPu4iekZQihLW9dyrWwzHt+ElAFPXgMqKJZ/WVg/VocHJwdRESBkgu58hQ8c273",
	"QLIBfBDGEh4tCANSWajQQmlcOZnttOQoUdLigwWDLP8Ctt7J3Uo7/HfcEvJr0nbcreZz8fIyLveG8M6U",
	"fvHBLISb3hjAB4tasgzC/fC///zXZ8d1ka08YXDUbwzdA0nGRE7TjklgGfF/NVqoUnIoje+4DvW/f3eM",
	"+l8GwZ3E78b8rMa8Dnb3syOVHDmC2yMzJvdRMwZ/b0Cuv77IcOZ/dw8nKZMrNMA0giqdWDCJKhCWSndW",
	"NJQ+lGVOQTGeCxnF0UJkmZCrO+8L5df/cTuQyxvMMGkm40ffKycCyIQ1niYef1fNOwVqIwzxsdKQMWPB",
	"bIRN0lOo6EjjNiZiMKjXqEdrlgnuxV1wuTNPXt653fiHEHRTGYv5TUOBp6R2X7uumcgILXvM+UfxgBzC",
	"dZFRJ+ZM36N2mKESFBmzFKbLh0hwkA7XlDY/e/rr/1CKjEO4XKtXXUpJVD209CkKrqG92vxQInsgvanx",
	"dGJKn0f3C3QDKFT2S/BxOJAfxclcHXTXvut/WKOuGhUqbOrY1u1zupxUI6FmXmExN8e41Ht7U+Y505Vr",
	"PB8P05pVByI3T8Rdr3Ra6LWIPaJYc7HSnmyn9N97WKuELcqMaS9Ua7IkdiC7xJe1HL59Ytg8T7dSXvui",
	"tSWY2nKthF9C188C72tq2wNjkiQeJqUWtroh1PiSLZBp1BclMcCuuxdJ4jYS6h4lCGNK2sBUXvwruRSr",
	"UtMWe1dTjOH3KilzlGGi0gbEK8S/Figvri4hkLzSwBX6CYtyqXRCI8i7+AFYaVNaOfGr6FJSwYzgCMiS",
	"FFImeeZT5rqAYvXRtElLrS2iLYUu5FLtR3hVLjKRwJ/n8ysKyWqW2KYB8+pzVdiGNscwT4UBHmIjaeBm",
	"ppCrDMGoktwnytWlTVs+9xYoalPqJUvwgz+hKJS2kCiOtNAKJWo39ZZa5SACPyhWiBHds0KnXK2whPTo",
	"p+pv/7iaw1VN6BdXlx1ankXT8dvxlLCoCpSsENEseu9+iqOC2dQVfsIKMVm/nRg3+SbtFFuhYzzqa5f5",
	"Sx7Noj+h7Y1IAqEplDQeRe+m0zAALYbNe1FkoXSTn42fAJ6sjlFZz46r3YBu2BlllMNm6o491msGi67R",
	"5XqTok1xeMoOPF/np79FeSpBfX32mhkaFIQHUpWUWhNcG20Xg7Eiy9xRhG/owTF0ppFo2fWekLUsM8A6",
	"urDVi9SgyPj5uMcz0exTn2E+3W5v+6Wxpa61547+qx0Po6PdIwabYwJ4UQ7U4qocqIXbdv2gePXVynBA",
	"6mz7FG11idtfChgGSke0hhDyQ30gOOaFIseASQ4sqH66RJuA0UYLi6ONoI3NScX2ntJmIqxoO/DsV3mo",
	"BQ+TE4m0ebjnFTPdUYQD6T1R3XWmG/pdduyfsjtqiWpg96XMibknrztLmwM+BF006LkIHafMQAm6x9Vu",
	"ymiWo0VtnGf9TH3MBBKjpsog0YbVFdxjNQONHDOxRhI6nhNYjnQJzprUuJ/2HT8n5KxR035cSat8fOEk",
	"o3+s6DQ1+ZEi404s+EPd6LIGflKN/oJVtNvFcQcn3ZPwd789to+6fR0CGnpH8I3Zp39oP9AWF1BoXAtV",
	"GgjFraBfzJ2011VrD4NJdfnSfWifcldp8ixZYv0ZjD9idyB9N3377UIceJXSPbf1uwzRxj/rNGIMwu6+",
	"KmgO1yk8K3I0luVF3DCBP5kaPoc/kRZ8bMD2/Ccbjdjfb7dBfp48+j8u+XbS8saocxJGqX6KPwYP2I+w",
	"yennv675SQe3rV87/mTPH92YPZPoYqhtwAKXSiMwWYEbq06HWot5YZGP4RodLGpqkwmCFhw9e581CPIH",
	"pecgmS01yzyZMtBYILNt26klDXPSfqP69L6TLSbNBrWBd9PpToN2bnLN9lUItKAwNa3yr7NPF6N/stG/",
	"p6Pfje7Gt49v4998vz3/LvpmPPrUOf035tPBDhim1f0Sem0hzAA0alL1L2U+HC7uazLpc4ObH3wHdoBL",
	"d948Ofj6DW3IAPepMGJBpKmG3j2h5IUSRBiltCJryQTr9/+nkqsL0pFr8ybFfY8ArCYsRtup3RcTH3ZD",
	"qr938K9ygS1t2MXuuAdn8+mvz19IzZP2C4rDLH3h7vlClt4QHXbrK0w4yq0/s3hNkr59xeYd+nrmALwH",
	"viiJQapN0N019ZuG+1tV6xWwN+XaQ9hUlZa4HRNFGqH5AOZEwPry+gOSwC694dnOCtPFH1nZbv8fAAD/",
	"/w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
