// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for CreatedTenantKind.
const (
	CreatedTenantKindBusiness CreatedTenantKind = "business"
)

// Valid indicates whether the value is a known member of the CreatedTenantKind enum.
func (e CreatedTenantKind) Valid() bool {
	switch e {
	case CreatedTenantKindBusiness:
		return true
	default:
		return false
	}
}

// Defines values for CreatedTenantRole.
const (
	CreatedTenantRoleOwner CreatedTenantRole = "owner"
)

// Valid indicates whether the value is a known member of the CreatedTenantRole enum.
func (e CreatedTenantRole) Valid() bool {
	switch e {
	case CreatedTenantRoleOwner:
		return true
	default:
		return false
	}
}

// Defines values for SystemStatusStatus.
const (
	Available SystemStatusStatus = "available"
)

// Valid indicates whether the value is a known member of the SystemStatusStatus enum.
func (e SystemStatusStatus) Valid() bool {
	switch e {
	case Available:
		return true
	default:
		return false
	}
}

// Defines values for TenantSummaryKind.
const (
	TenantSummaryKindBusiness TenantSummaryKind = "business"
	TenantSummaryKindPersonal TenantSummaryKind = "personal"
)

// Valid indicates whether the value is a known member of the TenantSummaryKind enum.
func (e TenantSummaryKind) Valid() bool {
	switch e {
	case TenantSummaryKindBusiness:
		return true
	case TenantSummaryKindPersonal:
		return true
	default:
		return false
	}
}

// Defines values for TenantSummaryRole.
const (
	TenantSummaryRoleAdmin         TenantSummaryRole = "admin"
	TenantSummaryRoleBillingMember TenantSummaryRole = "billing_member"
	TenantSummaryRoleMember        TenantSummaryRole = "member"
	TenantSummaryRoleOwner         TenantSummaryRole = "owner"
)

// Valid indicates whether the value is a known member of the TenantSummaryRole enum.
func (e TenantSummaryRole) Valid() bool {
	switch e {
	case TenantSummaryRoleAdmin:
		return true
	case TenantSummaryRoleBillingMember:
		return true
	case TenantSummaryRoleMember:
		return true
	case TenantSummaryRoleOwner:
		return true
	default:
		return false
	}
}

// CreateTenantRequest defines model for CreateTenantRequest.
type CreateTenantRequest struct {
	// DisplayName The business tenant's human-readable display name.
	DisplayName string `json:"display_name"`
}

// CreatedTenant defines model for CreatedTenant.
type CreatedTenant struct {
	// CreatedAt When the tenant was created.
	CreatedAt time.Time `json:"created_at"`

	// DisplayName The created tenant's display name, echoed back.
	DisplayName string `json:"display_name"`

	// Kind The tenant kind (T04 provisions business tenants only).
	Kind CreatedTenantKind `json:"kind"`

	// Role The membership role the creator holds in the new tenant.
	Role CreatedTenantRole `json:"role"`

	// TenantId The created tenant's immutable identifier.
	TenantId openapi_types.UUID `json:"tenant_id"`
}

// CreatedTenantKind The tenant kind (T04 provisions business tenants only).
type CreatedTenantKind string

// CreatedTenantRole The membership role the creator holds in the new tenant.
type CreatedTenantRole string

// SelectedTenantContext defines model for SelectedTenantContext.
type SelectedTenantContext struct {
	// SelectedAt When the selection was persisted or last switched.
	SelectedAt time.Time `json:"selected_at"`

	// TenantId The persisted, server-validated selected tenant.
	TenantId openapi_types.UUID `json:"tenant_id"`
}

// SystemStatus defines model for SystemStatus.
type SystemStatus struct {
	// Status Fixed availability marker for the platform service.
	Status SystemStatusStatus `json:"status"`

	// Version Build version of the running platform service.
	Version string `json:"version"`
}

// SystemStatusStatus Fixed availability marker for the platform service.
type SystemStatusStatus string

// TenantContextSelection defines model for TenantContextSelection.
type TenantContextSelection struct {
	// TenantId The tenant being selected.
	TenantId openapi_types.UUID `json:"tenant_id"`
}

// TenantList defines model for TenantList.
type TenantList struct {
	// Tenants Every tenant with an active membership for the user.
	Tenants []TenantSummary `json:"tenants"`
}

// TenantSummary defines model for TenantSummary.
type TenantSummary struct {
	// Kind The tenant kind (migration 000003 vocabulary).
	Kind TenantSummaryKind `json:"kind"`

	// Role The membership role the user holds in the tenant.
	Role TenantSummaryRole `json:"role"`

	// TenantId The tenant's immutable identifier.
	TenantId openapi_types.UUID `json:"tenant_id"`
}

// TenantSummaryKind The tenant kind (migration 000003 vocabulary).
type TenantSummaryKind string

// TenantSummaryRole The membership role the user holds in the tenant.
type TenantSummaryRole string

// CreateTenantParams defines parameters for CreateTenant.
type CreateTenantParams struct {
	// IdempotencyKey Client-chosen retry key: redelivering the same key (with the same authenticated user) converges onto the already-created tenant.
	IdempotencyKey string `json:"Idempotency-Key"`
}

// PutTenantContextJSONRequestBody defines body for PutTenantContext for application/json ContentType.
type PutTenantContextJSONRequestBody = TenantContextSelection

// CreateTenantJSONRequestBody defines body for CreateTenant for application/json ContentType.
type CreateTenantJSONRequestBody = CreateTenantRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// GetSystemStatus Report whether the platform service is available.
	// (GET /api/v1/system/status)
	GetSystemStatus(c *gin.Context)
	// GetTenantContext Return the server-validated current tenant context selection.
	// (GET /api/v1/tenant-context)
	GetTenantContext(c *gin.Context)
	// PutTenantContext Select or switch the current tenant context.
	// (PUT /api/v1/tenant-context)
	PutTenantContext(c *gin.Context)
	// ListTenants List the tenants the authenticated user holds an active membership in.
	// (GET /api/v1/tenants)
	ListTenants(c *gin.Context)
	// CreateTenant Create a business tenant owned by the authenticated user.
	// (POST /api/v1/tenants)
	CreateTenant(c *gin.Context, params CreateTenantParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetSystemStatus operation middleware
func (siw *ServerInterfaceWrapper) GetSystemStatus(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetSystemStatus(c)
}

// GetTenantContext operation middleware
func (siw *ServerInterfaceWrapper) GetTenantContext(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetTenantContext(c)
}

// PutTenantContext operation middleware
func (siw *ServerInterfaceWrapper) PutTenantContext(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PutTenantContext(c)
}

// ListTenants operation middleware
func (siw *ServerInterfaceWrapper) ListTenants(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListTenants(c)
}

// CreateTenant operation middleware
func (siw *ServerInterfaceWrapper) CreateTenant(c *gin.Context) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateTenantParams

	headers := c.Request.Header

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for Idempotency-Key, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter Idempotency-Key: %w", err), http.StatusBadRequest)
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter Idempotency-Key is required, but not found"), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateTenant(c, params)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/api/v1/system/status", wrapper.GetSystemStatus)
	router.GET(options.BaseURL+"/api/v1/tenants", wrapper.ListTenants)
	router.POST(options.BaseURL+"/api/v1/tenants", wrapper.CreateTenant)
	router.GET(options.BaseURL+"/api/v1/tenant-context", wrapper.GetTenantContext)
	router.PUT(options.BaseURL+"/api/v1/tenant-context", wrapper.PutTenantContext)
}

type GetSystemStatusRequestObject struct {
}

type GetSystemStatusResponseObject interface {
	VisitGetSystemStatusResponse(w http.ResponseWriter) error
}

type GetSystemStatus200JSONResponse SystemStatus

func (response GetSystemStatus200JSONResponse) VisitGetSystemStatusResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetTenantContextRequestObject struct {
}

type GetTenantContextResponseObject interface {
	VisitGetTenantContextResponse(w http.ResponseWriter) error
}

type GetTenantContext200JSONResponse SelectedTenantContext

func (response GetTenantContext200JSONResponse) VisitGetTenantContextResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type PutTenantContextRequestObject struct {
	Body *PutTenantContextJSONRequestBody
}

type PutTenantContextResponseObject interface {
	VisitPutTenantContextResponse(w http.ResponseWriter) error
}

type PutTenantContext200JSONResponse SelectedTenantContext

func (response PutTenantContext200JSONResponse) VisitPutTenantContextResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListTenantsRequestObject struct {
}

type ListTenantsResponseObject interface {
	VisitListTenantsResponse(w http.ResponseWriter) error
}

type ListTenants200JSONResponse TenantList

func (response ListTenants200JSONResponse) VisitListTenantsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type CreateTenantRequestObject struct {
	Params CreateTenantParams
	Body   *CreateTenantJSONRequestBody
}

type CreateTenantResponseObject interface {
	VisitCreateTenantResponse(w http.ResponseWriter) error
}

type CreateTenant200JSONResponse CreatedTenant

func (response CreateTenant200JSONResponse) VisitCreateTenantResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type CreateTenant201JSONResponse CreatedTenant

func (response CreateTenant201JSONResponse) VisitCreateTenantResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// GetSystemStatus Report whether the platform service is available.
	// (GET /api/v1/system/status)
	GetSystemStatus(ctx context.Context, request GetSystemStatusRequestObject) (GetSystemStatusResponseObject, error)
	// GetTenantContext Return the server-validated current tenant context selection.
	// (GET /api/v1/tenant-context)
	GetTenantContext(ctx context.Context, request GetTenantContextRequestObject) (GetTenantContextResponseObject, error)
	// PutTenantContext Select or switch the current tenant context.
	// (PUT /api/v1/tenant-context)
	PutTenantContext(ctx context.Context, request PutTenantContextRequestObject) (PutTenantContextResponseObject, error)
	// ListTenants List the tenants the authenticated user holds an active membership in.
	// (GET /api/v1/tenants)
	ListTenants(ctx context.Context, request ListTenantsRequestObject) (ListTenantsResponseObject, error)
	// CreateTenant Create a business tenant owned by the authenticated user.
	// (POST /api/v1/tenants)
	CreateTenant(ctx context.Context, request CreateTenantRequestObject) (CreateTenantResponseObject, error)
}

type StrictHandlerFunc func(ctx *gin.Context, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictGinServerOptions struct {
	// RequestErrorHandlerFunc is called when a request cannot be parsed or
	// decoded. It is invoked for JSON bind failures, form parse/bind errors,
	// multipart reader errors, media type parse errors, missing multipart
	// boundaries, and request body read errors. The default returns 400.
	RequestErrorHandlerFunc func(ctx *gin.Context, err error)
	// HandlerErrorFunc is called when the application handler (or any
	// middleware wrapping it) returns a non-nil error. The default returns 500.
	HandlerErrorFunc func(ctx *gin.Context, err error)
	// ResponseErrorHandlerFunc is called when the response object fails to
	// serialize (Visit*Response returns an error) or when the handler returns
	// an unexpected response type. The default returns 500.
	ResponseErrorHandlerFunc func(ctx *gin.Context, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictGinServerOptions{
		RequestErrorHandlerFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusBadRequest, gin.H{"msg": err.Error()})
		},
		HandlerErrorFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		},
		ResponseErrorHandlerFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictGinServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusBadRequest, gin.H{"msg": err.Error()})
		}
	}
	if options.HandlerErrorFunc == nil {
		options.HandlerErrorFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictGinServerOptions
}

// GetSystemStatus operation middleware
func (sh *strictHandler) GetSystemStatus(ctx *gin.Context) {
	var request GetSystemStatusRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetSystemStatus(ctx, request.(GetSystemStatusRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetSystemStatus")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(GetSystemStatusResponseObject); ok {
		if err := validResponse.VisitGetSystemStatusResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetTenantContext operation middleware
func (sh *strictHandler) GetTenantContext(ctx *gin.Context) {
	var request GetTenantContextRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetTenantContext(ctx, request.(GetTenantContextRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetTenantContext")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(GetTenantContextResponseObject); ok {
		if err := validResponse.VisitGetTenantContextResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PutTenantContext operation middleware
func (sh *strictHandler) PutTenantContext(ctx *gin.Context) {
	var request PutTenantContextRequestObject

	var body PutTenantContextJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PutTenantContext(ctx, request.(PutTenantContextRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PutTenantContext")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(PutTenantContextResponseObject); ok {
		if err := validResponse.VisitPutTenantContextResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListTenants operation middleware
func (sh *strictHandler) ListTenants(ctx *gin.Context) {
	var request ListTenantsRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListTenants(ctx, request.(ListTenantsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListTenants")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(ListTenantsResponseObject); ok {
		if err := validResponse.VisitListTenantsResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateTenant operation middleware
func (sh *strictHandler) CreateTenant(ctx *gin.Context, params CreateTenantParams) {
	var request CreateTenantRequestObject

	request.Params = params

	var body CreateTenantJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateTenant(ctx, request.(CreateTenantRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateTenant")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(CreateTenantResponseObject); ok {
		if err := validResponse.VisitCreateTenantResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"zFhtb9s4Ev4rBO+AawH5Je19OLif0t5bcD2crzGwWBRBQItjaxqJVPniVCj83xdDUpZky029uyk2n2JJ",
	"5Mw8M/M8Q37lua5qrUA5yxdfuc0LqET4950B4WAFSij3AT57sI4eCynRoVaiXBpdg3EIli82orSQ8br3",
	"6CuXaOtSNPdKVBB+g80N1rSaL/iqALb2FhVYy1ww8xfLCl8JNTEgpFiXwNIWjLaY8oxX4st7UFtX8MXV",
	"fJ7xCtXhd8ZdUwNfcOsMqi3f7zNu4LNHA5IvPg7duTt8rdefIHd8n6WIZQz5wljzuPZeuNNIfypAMVdA",
	"ipI9CsvS9xTTRpuKlnEpHEwcVsBPQsm+A8y0ZYdlH7yMQV5okGwt8ofpmIEHVDJEohVlmre54dmIrRQJ",
	"rWEvVvO/stroHVrUyh4n1TKtyublqE2jS+jb1I8KzKjBCqo1GFtgzWhRgDMErA0rdCktw4ixgsdkeNRi",
	"fHWP8jsxxKryLpQiSlAONwhmkDTvUfKnSq+zmnA+ymfWr58Ey1iF3kIJ+aFE32nl4MullWrTHt8u1fgV",
	"ahWqtQZj0RIw2rBSWMfsI7q8uKSAn0D+YCJjFswOzGQnSpQhG63LvcT+evz78Y9i3FgH1a0TzttLoT0s",
	"agta7ASWVD4nRf1P/AKSpfdYomtYJcwDGLbRJqSgLoWjMAMemMNoPe8INtrwGNO3HkvJ0mumN2FL45VC",
	"tR3d+hIqTYF25seAHBTpbVtPF0L6RNUkHloDRdVm9rfUx/lA3uPFApgI8NT1f+zANAc5QFcwoZjIHe4G",
	"TNdWgreRdNBBFXb7s4ENX/A/zTr1niXpnkVvb31VCdOExovxCGNEcyZy+424250uC71Vkyeko8KtEYFm",
	"5vT3mu10Lta+FCYqBihfkZvEDmSXZ50u3X1DUL5PQAjXoXp0BNNabiVJyAoVmceyRLW9j/tR38R/7i6n",
	"vOcXmTNCsicWzL1B19xS1cSUrUEYMNeeGODY3es8D4quH0AxtNbTJNFEFdZqg1tvQCbvXROnAQlmyv6u",
	"c1+BcjHJNAkswqr/1aCulzcskbw2TGqwTGnHQG20yUmCootvmPCuoJ3zuIvxihJmUQIDkResEEqWEbLQ",
	"BRRrjKYDrXCu5nsKHdVGn0a49OsSc/bv1WpJITkjcndowKr53NTuQJtTtirQMpliY2ijZqLalsCs9uQ+",
	"Ua7xruj4PFqgqK03G5HDG+aMULbWxrFcS6CNtqDABNXbGF0xTPygRY0T+mYLKggBOqp0/t/m/z8vV2zZ",
	"Evr18qZHyws+n15N51SLugYlauQL/jo8yngtXBESPxM1znZXMxuUb9ap2BYC41FfB+RvJF/wf4EbSCQV",
	"oa21srGKXs3nSQAdpCm6rsuUutknGxUgktVTVDawE3I3MjccSRlheFDdaaz1lsH4BwhYPxbgChhX2ZH1",
	"LT6xwSZ5N3adA2g4nz0nQqMD4Rmocm8MlethtsuYdViW4UwQG3pUhl4YIFoOvYeqHcssE725sJsXqUFB",
	"yJfTAc/wxcchw3y8298NU+O8aWfPo/mvdTxJR0pAZ3NKBV77kVws/Uguwln2rZbN75aGM6POfkjRznjY",
	"/1GKYSR1RGvAEj7UByihqjU5xoSSTKSpn17RIWDyaNDB5BGVvTDZ0VM6TKQdXa88h1kea8Hz5ERD2ip9",
	"84xI9ybCEXgvnO566gYyzCRZXOWOpiXKgTsdZS7EnrzubW3P+JDmolHPMXWctiMp6N8bBZUxogIHxgbP",
	"hki9KxGIUQttgWjDmYY9QLNgBiSUuAMadCIniAroFXtxgCY8OnX8JVXODswWLNPK6RhfSZzUTIbn+zBT",
	"kx8FCBmGhXi7wm/aws+byX+g4cddnPXqpH8l9epvT52j7p6HgMYu634w+wxvz0ba4prVBnaovWUpuQ0b",
	"JvMI9jZr3a0MTV0xdW+6VeEtKc9G5M4yYSDddYUifTW/+nEhjtxp9m/74ikDu/gXvUbMGLrjO7vDLReF",
	"57AC60RVZwcmCIeTMxdiF9JCjI2JE//JxmHYP203MrPf/xIAAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
